#include "biochem/BiochemEngine.hpp"
#include <cstdio>
#include <cmath>
#include <algorithm>

// =============================================================================
BiochemEngine::BiochemEngine()
{
    m_pool.reset();
}

// =============================================================================
//  loadDefaults
//  Builds a physiologically plausible starting state for a healthy creature.
//  This is the "factory genome" used for prototyping; Phase 3 will replace
//  this with genome-driven initialisation.
// =============================================================================
void BiochemEngine::loadDefaults()
{
    // -- Starting concentrations -----------------------------------------
    m_pool.set(Chem::GLUCOSE,       80.0f);   // reasonable blood sugar
    m_pool.set(Chem::OXYGEN,       200.0f);   // lungs full
    m_pool.set(Chem::ATP,           80.0f);   // energised
    m_pool.set(Chem::ADP,            0.0f);   // starts spent-free
    m_pool.set(Chem::WATER,        100.0f);
    m_pool.set(Chem::SLEEPINESS,    20.0f);   // slightly tired
    m_pool.set(Chem::WAKEFULNESS,   80.0f);
    m_pool.set(Chem::SEROTONIN,     50.0f);   // neutral mood
    m_pool.set(Chem::TIREDNESS,     10.0f);

    // -- Reactions --------------------------------------------------------

    // 1. Aerobic respiration (the ATP loop core):
    //    GLUCOSE + OXYGEN --> ATP + CO2
    //    kcat=8.0: at full concentrations produces 8*255 units/s — very fast
    {
        auto rxn = Reaction::make(
            Chem::GLUCOSE, 1.0f,
            Chem::OXYGEN,  1.0f,
            Chem::ATP,     2.0f,   // net 2 ATP per glucose (simplified)
            Chem::CO2,     1.0f,
            // kcat calibration: at glucose=80, O2=200 this yields ~5 ATP/s,
            // which comfortably covers walking (2.5/s) + brain (0.5/s) and lets
            // starvation or cyanide create a real deficit.
            0.04f,
            "aerobic_respiration");
        // Cyanide is a competitive inhibitor of cytochrome-c oxidase
        rxn.setInhibitor(Chem::CYANIDE, 0.95f);
        addReaction(rxn);
    }

    // NOTE: A standalone ADP → ATP reaction is intentionally absent.
    //   Real ATP synthase REQUIRES a proton gradient generated by oxidising glucose.
    //   Modelling it as ADP → ATP with any positive kcat creates free energy,
    //   causing ATP to regenerate without fuel — a fatal simulation bug.
    //   ADP is recycled implicitly: aerobic respiration consumes glucose and
    //   produces ATP directly; the ADP pool is just a bookkeeping store that
    //   shows how much energy has been spent. Phase 2 can refine this with
    //   a proton-motive-force intermediate if desired.

    // 2. Anaerobic fallback (when O2 is low):
    //    GLUCOSE --> ATP + LACTATE   (less efficient, 1 ATP per glucose)
    {
        auto rxn = Reaction::makeUnary(
            Chem::GLUCOSE, 1.0f,
            Chem::ATP,     1.0f,   // only 1 ATP (anaerobic is inefficient)
            Chem::LACTATE, 1.0f,
            0.012f, // ~30% of aerobic rate; kicks in when O2 is depleted
            "anaerobic_glycolysis");
        // Only runs meaningfully when O2 is depleted; aerobic takes priority
        // because it consumes glucose faster.  No explicit gating needed —
        // both reactions compete for the same glucose pool.
        addReaction(rxn);
    }

    // 4. Lactate clearance (liver converts lactate back to glucose precursors)
    //    LACTATE --> GLUCOSE  (simplified — real pathway is more complex)
    {
        addReaction(Reaction::makeSimple(
            Chem::LACTATE, Chem::GLUCOSE,
            0.5f,
            "lactate_clearance"));
    }

    // 5. Insulin-driven glucose storage (when blood glucose is very high):
    //    GLUCOSE + INSULIN --> stored (modelled as consumption)
    {
        addReaction(Reaction::make(
            Chem::GLUCOSE, 0.5f,
            Chem::INSULIN, 0.1f,
            Chem::NULL_CHEM, 0.0f,   // stored — gone from blood pool
            Chem::NULL_CHEM, 0.0f,
            3.0f,
            "glucose_storage"));
    }

    // -- Emitters --------------------------------------------------------

    // Oxygen supply: lungs passively replenish O2 (baseline breathing).
    // Modelled as constant drip; exertion will also increase O2 consumption.
    addEmitter(Emitter::makeConstant(
        Chem::OXYGEN, 5.0f, "lung_o2_supply"));

    // Glucose rising from digestion is handled by eatFood() directly.
    // But a tiny baseline drip represents liver glycogenolysis (resting state).
    addEmitter(Emitter::makeConstant(
        Chem::GLUCOSE, 0.5f, "liver_gluconeogenesis_baseline"));

    // Insulin release: when blood glucose > 100, pancreas emits insulin.
    addEmitter(Emitter::makeChemTriggered(
        Chem::GLUCOSE, 100.0f, 255.0f,
        Chem::INSULIN, 4.0f,
        "pancreas_insulin_release"));

    // Glucagon release: when blood glucose < 30, raise alarm.
    addEmitter(Emitter::makeChemTriggered(
        Chem::GLUCOSE, 0.0f, 30.0f,
        Chem::GLUCAGON, 3.0f,
        "pancreas_glucagon_release"));

    // Adrenaline spike when fear is high.
    addEmitter(Emitter::makeChemTriggered(
        Chem::FEAR, 100.0f, 255.0f,
        Chem::ADRENALINE, 15.0f,
        "adrenal_fear_spike"));

    // Tiredness builds while awake.
    addEmitter(Emitter::makeConstant(
        Chem::TIREDNESS, 0.3f, "tiredness_buildup"));

    // Melatonin emitted when tiredness is high (simplified — no day/night yet).
    addEmitter(Emitter::makeChemTriggered(
        Chem::TIREDNESS, 80.0f, 255.0f,
        Chem::MELATONIN, 5.0f,
        "pineal_melatonin_release"));

    // -- Receptors -------------------------------------------------------

    // Hunger for carbs: when glucose drops below 60, build HUNGER_CARB.
    addReceptor(Receptor::makeChemEmitter(
        Chem::GLUCOSE,
        0.0f, 60.0f,
        ReceptorTrigger::BELOW_THRESHOLD,
        Chem::HUNGER_CARB, 12.0f,
        "glucose_hunger_carb_receptor"));

    // Comfort rises with high ATP (creature feels well-energised).
    addReceptor(Receptor::makeChemEmitter(
        Chem::ATP,
        150.0f, 255.0f,
        ReceptorTrigger::ABOVE_THRESHOLD,
        Chem::COMFORT, 3.0f,
        "atp_comfort_receptor"));

    // Pain when lactate is very high (muscle ache).
    addReceptor(Receptor::makeChemEmitter(
        Chem::LACTATE,
        150.0f, 255.0f,
        ReceptorTrigger::ABOVE_THRESHOLD,
        Chem::PAIN, 8.0f,
        "lactate_pain_receptor"));

    // Sleepiness rises with melatonin.
    addReceptor(Receptor::makeChemEmitter(
        Chem::MELATONIN,
        50.0f, 255.0f,
        ReceptorTrigger::ABOVE_THRESHOLD,
        Chem::SLEEPINESS, 6.0f,
        "melatonin_sleepiness_receptor"));

    // Cyanide → pain (toxicity signal to brain).
    addReceptor(Receptor::makeChemEmitter(
        Chem::CYANIDE,
        10.0f, 255.0f,
        ReceptorTrigger::ABOVE_THRESHOLD,
        Chem::PAIN, 20.0f,
        "cyanide_pain_receptor"));

    m_alive      = true;
    m_ageSeconds = 0.0f;
}

// =============================================================================
//  Component registration
// =============================================================================
void BiochemEngine::addReaction(const Reaction& r) { m_reactions.push_back(r); }
void BiochemEngine::addEmitter (const Emitter&  e) { m_emitters.push_back(e);  }
void BiochemEngine::addReceptor(const Receptor& r) { m_receptors.push_back(r); }

void BiochemEngine::clearComponents()
{
    m_reactions.clear();
    m_emitters.clear();
    m_receptors.clear();
}

// =============================================================================
//  tick
// =============================================================================
void BiochemEngine::tick(float dt)
{
    if (!m_alive) return;

    m_ageSeconds += dt;

    // 1. Apply any queued external injections (food eaten, toxin events, etc.)
    applyInjections();

    // 2. Emitters (organ outputs into pool)
    for (auto& emitter : m_emitters)
        emitter.tick(m_pool, dt);

    // 3. Reactions (chemical transformations)
    for (const auto& rxn : m_reactions)
        rxn.tick(m_pool, dt);

    // 4. Receptors (pool → secondary chemicals or brain signals)
    for (const auto& rec : m_receptors)
        rec.tick(m_pool, dt);

    // 5. Decay
    m_pool.decay(dt);

    // 6. Death check
    checkDeath();
}

// =============================================================================
//  External events
// =============================================================================
void BiochemEngine::inject(uint8_t chemID, float amount)
{
    m_pendingInjections.push_back({chemID, amount});
}

void BiochemEngine::eatFood(float glucose, float aminoAcid,
                            float fattyAcid, float water)
{
    inject(Chem::GLUCOSE,    glucose);
    inject(Chem::AMINO_ACID, aminoAcid);
    inject(Chem::FATTY_ACID, fattyAcid);
    inject(Chem::WATER,      water);
}

void BiochemEngine::spendATP(float effort, float dt)
{
    // Walking:  ~2 units/s at effort=1
    // Running:  ~4 units/s at effort=2
    // Brain activity is modelled as a constant 0.5 units/s baseline
    //   and added to this call by the neural engine in Phase 2.
    static const float BASE_BRAIN_COST = 0.5f;
    float totalCost = (BASE_BRAIN_COST + effort * 2.0f) * dt;

    float consumed = m_pool.consume(Chem::ATP, totalCost);
    m_pool.add(Chem::ADP, consumed);   // spent ATP becomes ADP
}

// =============================================================================
//  Private helpers
// =============================================================================
void BiochemEngine::applyInjections()
{
    for (const auto& inj : m_pendingInjections)
        m_pool.add(inj.chemID, inj.amount);
    m_pendingInjections.clear();
}

void BiochemEngine::checkDeath()
{
    if (m_pool.get(Chem::ATP) <= ATP_DEATH_THRESHOLD)
    {
        m_alive = false;
        if (onDeath) onDeath("ATP starvation");
    }
}

// =============================================================================
//  Snapshot / debug
// =============================================================================
BiochemSnapshot BiochemEngine::snapshot() const
{
    BiochemSnapshot s;
    s.atp           = m_pool.get(Chem::ATP);
    s.adp           = m_pool.get(Chem::ADP);
    s.glucose       = m_pool.get(Chem::GLUCOSE);
    s.oxygen        = m_pool.get(Chem::OXYGEN);
    s.co2           = m_pool.get(Chem::CO2);
    s.hungerCarb    = m_pool.get(Chem::HUNGER_CARB);
    s.hungerProtein = m_pool.get(Chem::HUNGER_PROTEIN);
    s.hungerFat     = m_pool.get(Chem::HUNGER_FAT);
    s.sleepiness    = m_pool.get(Chem::SLEEPINESS);
    s.pain          = m_pool.get(Chem::PAIN);
    s.adrenaline    = m_pool.get(Chem::ADRENALINE);
    s.alive         = m_alive;
    s.ageSeconds    = m_ageSeconds;
    return s;
}

Emitter* BiochemEngine::findEmitter(const std::string& lbl) {
    for (auto& e : m_emitters)
        if (e.label() == lbl) return &e;
    return nullptr;
}

Reaction* BiochemEngine::findReaction(const std::string& lbl) {
    for (auto& r : m_reactions)
        if (r.label() == lbl) return &r;
    return nullptr;
}

void BiochemEngine::dumpSnapshot(const char* label) const
{
    auto s = snapshot();
    std::printf("--- BiochemSnapshot [%s] (age=%.1fs) ---\n",
                label ? label : "tick", s.ageSeconds);
    std::printf("  alive        : %s\n", s.alive ? "YES" : "NO (DEAD)");
    std::printf("  ATP          : %7.2f   ADP: %.2f\n", s.atp, s.adp);
    std::printf("  GLUCOSE      : %7.2f   O2:  %.2f   CO2: %.2f\n",
                s.glucose, s.oxygen, s.co2);
    std::printf("  hunger_carb  : %7.2f\n", s.hungerCarb);
    std::printf("  sleepiness   : %7.2f\n", s.sleepiness);
    std::printf("  pain         : %7.2f\n", s.pain);
    std::printf("  adrenaline   : %7.2f\n", s.adrenaline);
    std::printf("\n");
}
